import '../core/constants/api_constants.dart';
import '../models/report_model.dart';
import 'api_client.dart';

/// Service responsible for fetching the AI Doctor Report generated by the backend.
class ReportService {
  final _client = ApiClient.instance.dio;

  /// Fetches the weekly health report (last 7 days).
  Future<ReportModel> getWeeklyReport() async {
    final response = await _client.get(ApiConstants.weeklyReport);
    return ReportModel.fromJson(response.data as Map<String, dynamic>);
  }

  /// Fetches the monthly health report (last 30 days).
  Future<ReportModel> getMonthlyReport() async {
    final response = await _client.get(ApiConstants.monthlyReport);
    return ReportModel.fromJson(response.data as Map<String, dynamic>);
  }
}
